### ISSUE TITLE
fission.yaml does not result in a working deployment

### ISSUE THREAD

**Issue by SleepyBrett** [platform9/fission#31]
The yaml snippit for the controller deoployment ends in crash loop backoff with the following logs:

```
$ kcn fission logs controller-2839000588-pt9wb
2016/11/28 22:35:52 Error: path /filestore does not exist
```

**Comment by soamvasani** [comment]
Oof, the yaml uses the 'latest' tag for fission-bundle and that didn't point to a working image.  

I've tagged the current working fission-bundle image as 'latest' as well as 'alpha'.  Also, I'll update fission.yaml to use the 'alpha' tag.
