### ISSUE TITLE
Client CLI doesn't appear to match documentation

### ISSUE THREAD

**Issue by efexen** [platform9/fission#35]
I've just installed the Client CLI by following the instructions in the README.

Running `fission -v` confirms I am running v0.5.0

If I try to follow along and create the environment using `fission env create` I get following listing:

```
Usage: fission [options] COMMAND [arguments]
    -h, --help                       Displays this message
    -v, --version                    Output the version of fission

Commands:
clone                Clone a VM
delete               Delete a VM
info                 Show information for a VM
snapshot create      Create a snapshot of a VM
snapshot delete      Delete a snapshot of a VM
snapshot list        List the snapshots of a VM
snapshot revert      Revert a VM to a snapshot
start                Start a VM
status               Show the status of all VMs
stop                 Stop a VM
suspend              Suspend a VM
```

None of the commands seem to match any that are described in the documentation or the codebase here in Github?

Am I missing something completely?

Thanks,
Ville

**Comment by soamvasani** [comment]
Looks like you're running the wrong fission :)  I googled that help message and it looks like you're running https://github.com/thbishop/fission , which is an unrelated project.

**Comment by efexen** [comment]
😮  That makes sense:

`which fission` return `/Users/ville/.rbenv/shims/fission`

This might cause trouble, thanks for quick reply
